/*** Generated by streamline 0.10.15 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename, false),__func=__rt.__func,__cb=__rt.__cb,__catch=__rt.__catch,__tryCatch=__rt.__tryCatch; (function() {
  var GraphDatabase, JSON_KEY, Node, PACKAGE, Relationship, adjustError, status, util, __bind = function(fn, me) {
    return function() { return fn.apply(me, arguments); }; };

  PACKAGE = require("../package");

  status = require("http-status");

  util = require("./util");

  adjustError = util.adjustError;

  Relationship = require("./Relationship");

  Node = require("./Node");

  JSON_KEY = "_nodeNeo4j";

  module.exports = GraphDatabase = (function() {
    function GraphDatabase(opts) {
      this.reviveJSON = __bind(this.reviveJSON, this);
      opts = ((typeof opts === "string") ? {
        url: opts
      } : opts);
      this.url = opts.url;
      this._request = util.wrapRequest(opts);
      this._root = null;
      this._services = null; };





    GraphDatabase.prototype._purgeCache = function() {
      this._root = null;
      return this._services = null; };


    GraphDatabase.prototype._getRoot = function GraphDatabase_prototype__getRoot__1(_) { var error, response, __this = this; var __frame = { name: "GraphDatabase_prototype__getRoot__1", line: 39 }; return __func(_, this, arguments, GraphDatabase_prototype__getRoot__1, 0, __frame, function __$GraphDatabase_prototype__getRoot__1() {

        if ((__this._root != null)) {
          return _(null, __this._root); } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype__getRoot__1() {


              return __this._request.get(__this.url, __cb(_, __frame, 6, 33, function ___(__0, __1) { response = __1;
                if ((response.statusCode !== status.OK)) {
                  return _(response); } ;

                return _(null, __this._root = response.body); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype__getRoot__1() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype__getRoot__1() { _(); }); }); }); };



    GraphDatabase.prototype.getServices = function GraphDatabase_prototype_getServices__2(_) { var error, response, root, __this = this; var __frame = { name: "GraphDatabase_prototype_getServices__2", line: 56 }; return __func(_, this, arguments, GraphDatabase_prototype_getServices__2, 0, __frame, function __$GraphDatabase_prototype_getServices__2() {

        if ((__this._services != null)) {
          return _(null, __this._services); } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getServices__2() {


              return __this._getRoot(__cb(_, __frame, 6, 20, function ___(__0, __1) { root = __1;
                return __this._request.get(root.data, __cb(_, __frame, 7, 33, function ___(__0, __2) { response = __2;
                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, __this._services = response.body); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getServices__2() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getServices__2() { _(); }); }); }); };






    GraphDatabase.prototype.createNode = function(data) {
      var node;
      data = (data || { });
      node = new Node(this, {
        data: data });

      return node; };


    GraphDatabase.prototype.getNode = function GraphDatabase_prototype_getNode__3(url, _) { var error, response, __this = this; var __frame = { name: "GraphDatabase_prototype_getNode__3", line: 86 }; return __func(_, this, arguments, GraphDatabase_prototype_getNode__3, 1, __frame, function __$GraphDatabase_prototype_getNode__3() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getNode__3() {


              return __this._request.get(url, __cb(_, __frame, 3, 33, function ___(__0, __1) { response = __1;
                if ((response.statusCode !== status.OK)) {
                  if ((response.statusCode === status.NOT_FOUND)) {
                    return _(new Error(("No node at " + url))); } ;

                  return _(response); } ;

                return _(null, new Node(__this, response.body)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getNode__3() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getNode__3() { _(); }); }); }); };



    GraphDatabase.prototype.getNodeById = function GraphDatabase_prototype_getNodeById__4(id, _) { var error, node, services, url, __this = this; var __frame = { name: "GraphDatabase_prototype_getNodeById__4", line: 103 }; return __func(_, this, arguments, GraphDatabase_prototype_getNodeById__4, 1, __frame, function __$GraphDatabase_prototype_getNodeById__4() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getNodeById__4() {


              return __this.getServices(__cb(_, __frame, 3, 24, function ___(__0, __1) { services = __1;
                url = ((("" + services.node) + "/") + id);
                return __this.getNode(url, __cb(_, __frame, 5, 20, function ___(__0, __2) { node = __2;
                  return _(null, node); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getNodeById__4() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getNodeById__4() { _(); }); }); }); };



    GraphDatabase.prototype.getIndexedNode = function GraphDatabase_prototype_getIndexedNode__5(index, property, value, _) { var error, node, nodes, __this = this; var __frame = { name: "GraphDatabase_prototype_getIndexedNode__5", line: 116 }; return __func(_, this, arguments, GraphDatabase_prototype_getIndexedNode__5, 3, __frame, function __$GraphDatabase_prototype_getIndexedNode__5() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedNode__5() {


              return __this.getIndexedNodes(index, property, value, __cb(_, __frame, 3, 21, function ___(__0, __1) { nodes = __1;
                node = null;
                if ((nodes && (nodes.length > 0))) {
                  node = nodes[0]; } ;

                return _(null, node); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getIndexedNode__5() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedNode__5() { _(); }); }); }); };



    GraphDatabase.prototype.getIndexedNodes = function GraphDatabase_prototype_getIndexedNodes__6(index, property, value, _) { var error, key, response, services, url, val, __this = this; var __frame = { name: "GraphDatabase_prototype_getIndexedNodes__6", line: 131 }; return __func(_, this, arguments, GraphDatabase_prototype_getIndexedNodes__6, 3, __frame, function __$GraphDatabase_prototype_getIndexedNodes__6() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedNodes__6() {


              return __this.getServices(__cb(_, __frame, 3, 24, function ___(__0, __1) { services = __1;
                key = encodeURIComponent(property);
                val = encodeURIComponent(value);
                url = ((((((("" + services.node_index) + "/") + index) + "/") + key) + "/") + val);
                return __this._request.get(url, __cb(_, __frame, 7, 33, function ___(__0, __2) { response = __2;
                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, response.body.map((function(_this) {
                    return function(node) {
                      return new Node(_this, node); };

                  })(__this))); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getIndexedNodes__6() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedNodes__6() { _(); }); }); }); };



    GraphDatabase.prototype.queryNodeIndex = function GraphDatabase_prototype_queryNodeIndex__7(index, query, _) { var error, response, services, url, __this = this; var __frame = { name: "GraphDatabase_prototype_queryNodeIndex__7", line: 153 }; return __func(_, this, arguments, GraphDatabase_prototype_queryNodeIndex__7, 2, __frame, function __$GraphDatabase_prototype_queryNodeIndex__7() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_queryNodeIndex__7() {


              return __this.getServices(__cb(_, __frame, 3, 24, function ___(__0, __1) { services = __1;
                url = ((((("" + services.node_index) + "/") + index) + "?query=") + (encodeURIComponent(query)));
                return __this._request.get(url, __cb(_, __frame, 5, 33, function ___(__0, __2) { response = __2;
                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, response.body.map((function(_this) {
                    return function(node) {
                      return new Node(_this, node); };

                  })(__this))); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_queryNodeIndex__7() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_queryNodeIndex__7() { _(); }); }); }); };






    GraphDatabase.prototype.createRelationship = function GraphDatabase_prototype_createRelationship__8(startNode, endNode, type, _) { var __frame = { name: "GraphDatabase_prototype_createRelationship__8", line: 176 }; return __func(_, this, arguments, GraphDatabase_prototype_createRelationship__8, 3, __frame, function __$GraphDatabase_prototype_createRelationship__8() { _(); }); };

    GraphDatabase.prototype.getRelationship = function GraphDatabase_prototype_getRelationship__9(url, _) { var error, response, __this = this; var __frame = { name: "GraphDatabase_prototype_getRelationship__9", line: 178 }; return __func(_, this, arguments, GraphDatabase_prototype_getRelationship__9, 1, __frame, function __$GraphDatabase_prototype_getRelationship__9() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getRelationship__9() {


              return __this._request.get(url, __cb(_, __frame, 3, 33, function ___(__0, __1) { response = __1;
                if ((response.statusCode !== status.OK)) {
                  return _(response); } ;

                return _(null, new Relationship(__this, response.body)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getRelationship__9() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getRelationship__9() { _(); }); }); }); };



    GraphDatabase.prototype.getRelationshipById = function GraphDatabase_prototype_getRelationshipById__10(id, _) { var relationshipURL, services, url, __this = this; var __frame = { name: "GraphDatabase_prototype_getRelationshipById__10", line: 192 }; return __func(_, this, arguments, GraphDatabase_prototype_getRelationshipById__10, 1, __frame, function __$GraphDatabase_prototype_getRelationshipById__10() {

        return __this.getServices(__cb(_, __frame, 2, 22, function ___(__0, __1) { services = __1;
          relationshipURL = services.node.replace("node", "relationship");
          url = ((("" + relationshipURL) + "/") + id);
          return __this.getRelationship(url, __cb(_, __frame, 5, 18, _, true)); }, true)); }); };


    GraphDatabase.prototype.getIndexedRelationship = function GraphDatabase_prototype_getIndexedRelationship__11(index, property, value, _) { var error, relationships, __this = this; var __frame = { name: "GraphDatabase_prototype_getIndexedRelationship__11", line: 200 }; return __func(_, this, arguments, GraphDatabase_prototype_getIndexedRelationship__11, 3, __frame, function __$GraphDatabase_prototype_getIndexedRelationship__11() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedRelationship__11() {


              return __this.getIndexedRelationships(index, property, value, __cb(_, __frame, 3, 29, function ___(__0, __1) { relationships = __1;
                return _(null, ((((relationships != null) ? relationships[0] : void 0)) || null)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getIndexedRelationship__11() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedRelationship__11() { _(); }); }); }); };



    GraphDatabase.prototype.getIndexedRelationships = function GraphDatabase_prototype_getIndexedRelationships__12(index, property, value, _) { var error, key, response, services, url, val, __this = this; var __frame = { name: "GraphDatabase_prototype_getIndexedRelationships__12", line: 211 }; return __func(_, this, arguments, GraphDatabase_prototype_getIndexedRelationships__12, 3, __frame, function __$GraphDatabase_prototype_getIndexedRelationships__12() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedRelationships__12() {


              return __this.getServices(__cb(_, __frame, 3, 24, function ___(__0, __1) { services = __1;
                key = encodeURIComponent(property);
                val = encodeURIComponent(value);
                url = ((((((("" + services.relationship_index) + "/") + index) + "/") + key) + "/") + val);
                return __this._request.get(url, __cb(_, __frame, 7, 33, function ___(__0, __2) { response = __2;
                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, response.body.map((function(_this) {
                    return function(relationship) {
                      return new Relationship(_this, relationship); };

                  })(__this))); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getIndexedRelationships__12() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getIndexedRelationships__12() { _(); }); }); }); };



    GraphDatabase.prototype.queryRelationshipIndex = function GraphDatabase_prototype_queryRelationshipIndex__13(index, query, _) { var error, response, services, url, __this = this; var __frame = { name: "GraphDatabase_prototype_queryRelationshipIndex__13", line: 233 }; return __func(_, this, arguments, GraphDatabase_prototype_queryRelationshipIndex__13, 2, __frame, function __$GraphDatabase_prototype_queryRelationshipIndex__13() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_queryRelationshipIndex__13() {


              return __this.getServices(__cb(_, __frame, 3, 24, function ___(__0, __1) { services = __1;
                url = ((((("" + services.relationship_index) + "/") + index) + "?query=") + (encodeURIComponent(query)));
                return __this._request.get(url, __cb(_, __frame, 5, 33, function ___(__0, __2) { response = __2;
                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, response.body.map((function(_this) {
                    return function(relationship) {
                      return new Relationship(_this, relationship); };

                  })(__this))); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_queryRelationshipIndex__13() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_queryRelationshipIndex__13() { _(); }); }); }); };






    GraphDatabase.prototype.getNodeIndexes = function GraphDatabase_prototype_getNodeIndexes__14(_) { var arr, error, map, name, props, response, services, _ref, __this = this; var __frame = { name: "GraphDatabase_prototype_getNodeIndexes__14", line: 256 }; return __func(_, this, arguments, GraphDatabase_prototype_getNodeIndexes__14, 0, __frame, function __$GraphDatabase_prototype_getNodeIndexes__14() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getNodeIndexes__14() {


              return __this.getServices(__cb(_, __frame, 3, 24, function ___(__0, __1) { services = __1;
                return __this._request.get(services.node_index, __cb(_, __frame, 4, 33, function ___(__0, __2) { response = __2;
                  if ((((_ref = response.statusCode) !== status.OK) && (_ref !== status.NO_CONTENT))) {
                    return _(response); } ;

                  map = (response.body || { });
                  arr = [];
                  for (name in map) {
                    props = map[name];
                    arr.push(name);
                    arr[name] = props; };

                  return _(null, arr); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getNodeIndexes__14() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getNodeIndexes__14() { _(); }); }); }); };



    GraphDatabase.prototype.createNodeIndex = function GraphDatabase_prototype_createNodeIndex__15(name, config, _) { var error, response, services, __this = this; var __frame = { name: "GraphDatabase_prototype_createNodeIndex__15", line: 278 }; return __func(_, this, arguments, GraphDatabase_prototype_createNodeIndex__15, 2, __frame, function __$GraphDatabase_prototype_createNodeIndex__15() {

        if ((config == null)) {
          config = { }; } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_createNodeIndex__15() {


              return __this.getServices(__cb(_, __frame, 6, 24, function ___(__0, __1) { services = __1;
                return __this._request.post({
                  url: services.node_index,
                  json: {
                    name: name,
                    config: config } }, __cb(_, __frame, 7, 33, function ___(__0, __2) { response = __2;


                  if ((response.statusCode !== status.CREATED)) {
                    return _(response); } ; __then(); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_createNodeIndex__15() { if (_error) {


                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_createNodeIndex__15() { _(); }); }); }); };



    (function(actual) {
      return GraphDatabase.prototype.createNodeIndex = function(name, config, callback) {
        if ((typeof config === "function")) {
          callback = config;
          config = null; } ;

        return actual.call(this, name, config, callback); };

    })(GraphDatabase.prototype.createNodeIndex);

    GraphDatabase.prototype.deleteNodeIndex = function GraphDatabase_prototype_deleteNodeIndex__16(name, _) { var error, response, services, __this = this; var __frame = { name: "GraphDatabase_prototype_deleteNodeIndex__16", line: 311 }; return __func(_, this, arguments, GraphDatabase_prototype_deleteNodeIndex__16, 1, __frame, function __$GraphDatabase_prototype_deleteNodeIndex__16() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_deleteNodeIndex__16() {


              return __this.getServices(__cb(_, __frame, 3, 24, function ___(__0, __1) { services = __1;
                return __this._request.del({
                  url: ((("" + services.node_index) + "/") + (encodeURIComponent(name))) }, __cb(_, __frame, 4, 33, function ___(__0, __2) { response = __2;

                  if ((response.statusCode !== status.NO_CONTENT)) {
                    return _(response); } ; __then(); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_deleteNodeIndex__16() { if (_error) {


                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_deleteNodeIndex__16() { _(); }); }); }); };



    GraphDatabase.prototype.getRelationshipIndexes = function GraphDatabase_prototype_getRelationshipIndexes__17(_) { var arr, error, map, name, props, response, services, _ref, __this = this; var __frame = { name: "GraphDatabase_prototype_getRelationshipIndexes__17", line: 327 }; return __func(_, this, arguments, GraphDatabase_prototype_getRelationshipIndexes__17, 0, __frame, function __$GraphDatabase_prototype_getRelationshipIndexes__17() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_getRelationshipIndexes__17() {


              return __this.getServices(__cb(_, __frame, 3, 24, function ___(__0, __1) { services = __1;
                return __this._request.get(services.relationship_index, __cb(_, __frame, 4, 33, function ___(__0, __2) { response = __2;
                  if ((((_ref = response.statusCode) !== status.OK) && (_ref !== status.NO_CONTENT))) {
                    return _(response); } ;

                  map = (response.body || { });
                  arr = [];
                  for (name in map) {
                    props = map[name];
                    arr.push(name);
                    arr[name] = props; };

                  return _(null, arr); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_getRelationshipIndexes__17() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_getRelationshipIndexes__17() { _(); }); }); }); };



    GraphDatabase.prototype.createRelationshipIndex = function GraphDatabase_prototype_createRelationshipIndex__18(name, config, _) { var error, response, services, __this = this; var __frame = { name: "GraphDatabase_prototype_createRelationshipIndex__18", line: 349 }; return __func(_, this, arguments, GraphDatabase_prototype_createRelationshipIndex__18, 2, __frame, function __$GraphDatabase_prototype_createRelationshipIndex__18() {

        if ((config == null)) {
          config = { }; } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_createRelationshipIndex__18() {


              return __this.getServices(__cb(_, __frame, 6, 24, function ___(__0, __1) { services = __1;
                return __this._request.post({
                  url: (("" + services.relationship_index) + "/"),
                  json: {
                    name: name,
                    config: config } }, __cb(_, __frame, 7, 33, function ___(__0, __2) { response = __2;


                  if ((response.statusCode !== status.CREATED)) {
                    return _(response); } ; __then(); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_createRelationshipIndex__18() { if (_error) {


                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_createRelationshipIndex__18() { _(); }); }); }); };



    (function(actual) {
      return GraphDatabase.prototype.createRelationshipIndex = function(name, config, callback) {
        if ((typeof config === "function")) {
          callback = config;
          config = null; } ;

        return actual.call(this, name, config, callback); };

    })(GraphDatabase.prototype.createRelationshipIndex);

    GraphDatabase.prototype.deleteRelationshipIndex = function GraphDatabase_prototype_deleteRelationshipIndex__19(name, _) { var error, response, services, __this = this; var __frame = { name: "GraphDatabase_prototype_deleteRelationshipIndex__19", line: 382 }; return __func(_, this, arguments, GraphDatabase_prototype_deleteRelationshipIndex__19, 1, __frame, function __$GraphDatabase_prototype_deleteRelationshipIndex__19() { return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_deleteRelationshipIndex__19() {


              return __this.getServices(__cb(_, __frame, 3, 24, function ___(__0, __1) { services = __1;
                return __this._request.del({
                  url: ((("" + services.relationship_index) + "/") + (encodeURIComponent(name))) }, __cb(_, __frame, 4, 33, function ___(__0, __2) { response = __2;

                  if ((response.statusCode !== status.NO_CONTENT)) {
                    return _(response); } ; __then(); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_deleteRelationshipIndex__19() { if (_error) {


                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_deleteRelationshipIndex__19() { _(); }); }); }); };



    GraphDatabase.prototype._toJSON = function(obj) {
      var json;
      json = { };
      json[JSON_KEY] = {
        version: PACKAGE.version,
        constructor: obj.constructor.name };

      return json; };


    GraphDatabase.prototype.fromJSON = function(obj) {
      var Constructor, meta;
      meta = ((obj != null) ? obj[JSON_KEY] : void 0);
      if ((typeof (((meta != null) ? meta.constructor : void 0)) !== "string")) {
        throw new Error(("Invalid JSON object: " + (JSON.stringify(obj)))); } ;

      Constructor = require(("./" + meta.constructor));
      return Constructor._fromJSON(this, obj); };


    GraphDatabase.prototype.reviveJSON = function(key, val) {
      var _ref;
      if ((typeof (((val != null) ? (((_ref = val[JSON_KEY]) != null) ? _ref.constructor : void 0) : void 0)) === "string")) {
        return this.fromJSON(val); }
       else {
        return val; } ; };






    GraphDatabase.prototype.query = function GraphDatabase_prototype_query__20(query, params, _) { var body, columns, endpoint, error, i, map, response, results, row, services, value, _ref, _ref1, __this = this; var __frame = { name: "GraphDatabase_prototype_query__20", line: 430 }; return __func(_, this, arguments, GraphDatabase_prototype_query__20, 2, __frame, function __$GraphDatabase_prototype_query__20() {

        if ((params == null)) {
          params = { }; } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_query__20() {


              return __this.getServices(__cb(_, __frame, 6, 24, function ___(__0, __1) { services = __1;
                endpoint = (services.cypher || ((((_ref = services.extensions) != null) ? (((_ref1 = _ref.CypherPlugin) != null) ? _ref1["execute_query"] : void 0) : void 0)));
                if (!endpoint) {
                  return _(new Error("Cypher plugin not installed")); } ;

                if ((typeof query !== "string")) {
                  return _(new Error((("Expected string query; got " + (typeof query)) + "."))); } ;

                return __this._request.post({
                  uri: endpoint,
                  json: {
                    query: query,
                    params: params } }, __cb(_, __frame, 14, 33, function ___(__0, __2) { response = __2;


                  if ((response.statusCode === status.NO_CONTENT)) {
                    return _(new Error((("Unknown Neo4j error for query:\n\n" + query) + "\n"))); } ;

                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  body = response.body;
                  if ((typeof body !== "object")) {
                    return _(new Error((("Malformed Cypher response for query:\n\n" + query) + "\n\nNeo4j may have run out of memory processing this query.\nMaybe try a more efficient query?"))); } ;

                  columns = body.columns;














                  return (function ___closure(_) { var _i, _j, _len, _len1, _ref2, _results; _ref2 = body.data; _results = []; for (_i = 0, _len = _ref2.length; (_i < _len); _i++) { row = _ref2[_i]; map = { }; for (i = _j = 0, _len1 = row.length; (_j < _len1); i = ++_j) { value = row[i]; map[columns[i]] = util.transform(value, __this); }; _results.push(map); }; return _(null, _results); })(__cb(_, __frame, 32, 18, function ___(__0, __3) { results = __3;
                    return _(null, results); }, true)); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_query__20() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_query__20() { _(); }); }); }); };



    (function(actual) {
      return GraphDatabase.prototype.query = function(query, params, callback) {
        if (((typeof query === "function") && (typeof params === "string"))) {
          console.warn((("neo4j.GraphDatabase::query()’s signature is " + "now (query, params, callback). Please update your code!\n") + new Error().stack.split("\n")[2]));
          callback = query;
          query = params;
          params = null; }
         else if ((typeof params === "function")) {
          callback = params;
          params = null; }  ;

        return actual.call(this, query, params, callback); };

    })(GraphDatabase.prototype.query);

    GraphDatabase.prototype.execute = function GraphDatabase_prototype_execute__21(script, params, _) { var endpoint, error, response, services, _ref, _ref1, __this = this; var __frame = { name: "GraphDatabase_prototype_execute__21", line: 499 }; return __func(_, this, arguments, GraphDatabase_prototype_execute__21, 2, __frame, function __$GraphDatabase_prototype_execute__21() {

        if ((params == null)) {
          params = { }; } ; return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$GraphDatabase_prototype_execute__21() {


              return __this.getServices(__cb(_, __frame, 6, 24, function ___(__0, __1) { services = __1;
                endpoint = (((_ref = services.extensions) != null) ? (((_ref1 = _ref.GremlinPlugin) != null) ? _ref1["execute_script"] : void 0) : void 0);
                if (!endpoint) {
                  return _(new Error("Gremlin plugin not installed")); } ;

                return __this._request.post({
                  uri: endpoint,
                  json: {
                    script: script,
                    params: params } }, __cb(_, __frame, 11, 33, function ___(__0, __2) { response = __2;


                  if ((response.statusCode === status.NO_CONTENT)) {
                    return _(new Error((("Unknown Neo4j error for Gremlin script:\n\n" + script) + "\n"))); } ;

                  if ((response.statusCode !== status.OK)) {
                    return _(response); } ;

                  return _(null, util.transform(response.body, __this)); }, true)); }, true)); }); })(function ___(_error, __result) { __catch(function __$GraphDatabase_prototype_execute__21() { if (_error) {

                error = _error;
                return _(adjustError(error)); } else { _(null, __result); } ; }, _); }); })(function ___() { __tryCatch(_, function __$GraphDatabase_prototype_execute__21() { _(); }); }); }); };



    (function(actual) {
      return GraphDatabase.prototype.execute = function(script, params, callback) {
        if ((typeof params === "function")) {
          callback = params;
          params = null; } ;

        return actual.call(this, script, params, callback); };

    })(GraphDatabase.prototype.execute);

    return GraphDatabase;

  })();

}).call(this);
